steps:
  - name: gcr.io/kaniko-project/executor:latest
    args:
      - --cache=true
      - --cache-ttl=24h
      - --destination=asia-northeast1-docker.pkg.dev/miniature-enigma/docker/back:latest
      - --destination=asia-northeast1-docker.pkg.dev/miniature-enigma/docker/back:$COMMIT_SHA
      - --dockerfile=back/Dockerfile

  - name: gcr.io/kaniko-project/executor:latest
    args:
      - --cache=true
      - --cache-ttl=24h
      - --destination=asia-northeast1-docker.pkg.dev/miniature-enigma/docker/front:latest
      - --destination=asia-northeast1-docker.pkg.dev/miniature-enigma/docker/front:$COMMIT_SHA
      - --dockerfile=front/Dockerfile

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - back
      - --image
      - asia-northeast1-docker.pkg.dev/miniature-enigma/docker/back:$COMMIT_SHA
      - --region
      - asia-northeast1

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - front
      - --image
      - asia-northeast1-docker.pkg.dev/miniature-enigma/docker/front:$COMMIT_SHA
      - --region
      - asia-northeast1
